openapi: 3.0.0
info:
  title: CheckoutService API
  version: 1.0.0
  description: REST API representation of the CheckoutService gRPC service.
servers:
  - url: https://api.example.com
paths:
  /checkout/placeOrder:
    post:
      summary: Place an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOrderRequest'
      responses:
        '200':
          description: Order placed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceOrderResponse'
components:
  schemas:
    Address:
      type: object
      properties:
        street_address:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        zip_code:
          type: string
    CreditCardInfo:
      type: object
      properties:
        credit_card_number:
          type: string
        credit_card_cvv:
          type: integer
        credit_card_expiration_year:
          type: integer
        credit_card_expiration_month:
          type: integer
    Money:
      type: object
      properties:
        currency_code:
          type: string
        units:
          type: integer
        nanos:
          type: integer
    CartItem:
      type: object
      properties:
        product_id:
          type: string
        quantity:
          type: integer
    OrderItem:
      type: object
      properties:
        item:
          $ref: '#/components/schemas/CartItem'
        cost:
          $ref: '#/components/schemas/Money'
    OrderResult:
      type: object
      properties:
        order_id:
          type: string
        shipping_tracking_id:
          type: string
        shipping_cost:
          $ref: '#/components/schemas/Money'
        shipping_address:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    PlaceOrderRequest:
      type: object
      properties:
        user_id:
          type: string
        user_currency:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        email:
          type: string
        credit_card:
          $ref: '#/components/schemas/CreditCardInfo'
    PlaceOrderResponse:
      type: object
      properties:
        order:
          $ref: '#/components/schemas/OrderResult'
          