openapi: 3.0.0
info:
  title: ShippingService API
  version: 1.0.0
  description: REST API representation of the ShippingService gRPC service.
servers:
  - url: https://api.example.com
paths:
  /shipping/quote:
    post:
      summary: Get a shipping quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetQuoteRequest'
      responses:
        '200':
          description: Quote retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuoteResponse'
  /shipping/order:
    post:
      summary: Ship an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShipOrderRequest'
      responses:
        '200':
          description: Order shipped successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShipOrderResponse'
components:
  schemas:
    Address:
      type: object
      properties:
        street_address:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        zip_code:
          type: string
    CartItem:
      type: object
      properties:
        product_id:
          type: string
        quantity:
          type: integer
    Money:
      type: object
      properties:
        currency_code:
          type: string
        units:
          type: integer
        nanos:
          type: integer
    GetQuoteRequest:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    GetQuoteResponse:
      type: object
      properties:
        cost_usd:
          $ref: '#/components/schemas/Money'
    ShipOrderRequest:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    ShipOrderResponse:
      type: object
      properties:
        tracking_id:
          type: string
          